// Generated by delombok at Tue Apr 30 16:25:30 EDT 2019
/*
 * Copyright 2019 Noblis, Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.noblis.ties.data_binding;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({"collectionId", "collectionIdLabel", "collectionIdAlias", "collectionDescription", "subCollectionId", "subCollectionIdLabel", "subCollectionIdAlias", "subCollectionDescription", "registrationDate", "expirationDate", "owner", "securityTag"})
public class AuthorityInformation {
    @JsonProperty("collectionId")
    private String collectionId;
    @JsonProperty("collectionIdLabel")
    private String collectionIdLabel;
    @JsonProperty("collectionIdAlias")
    private String collectionIdAlias;
    @JsonProperty("collectionDescription")
    private String collectionDescription;
    @JsonProperty("subCollectionId")
    private String subCollectionId;
    @JsonProperty("subCollectionIdLabel")
    private String subCollectionIdLabel;
    @JsonProperty("subCollectionIdAlias")
    private String subCollectionIdAlias;
    @JsonProperty("subCollectionDescription")
    private String subCollectionDescription;
    @JsonProperty("registrationDate")
    private Date registrationDate;
    @JsonProperty("expirationDate")
    private Date expirationDate;
    @JsonProperty("owner")
    private String owner;
    @JsonProperty("securityTag")
    private String securityTag;

    @java.lang.SuppressWarnings("all")
    public AuthorityInformation() {
    }

    @java.lang.SuppressWarnings("all")
    public AuthorityInformation(final String collectionId, final String collectionIdLabel, final String collectionIdAlias, final String collectionDescription, final String subCollectionId, final String subCollectionIdLabel, final String subCollectionIdAlias, final String subCollectionDescription, final Date registrationDate, final Date expirationDate, final String owner, final String securityTag) {
        this.collectionId = collectionId;
        this.collectionIdLabel = collectionIdLabel;
        this.collectionIdAlias = collectionIdAlias;
        this.collectionDescription = collectionDescription;
        this.subCollectionId = subCollectionId;
        this.subCollectionIdLabel = subCollectionIdLabel;
        this.subCollectionIdAlias = subCollectionIdAlias;
        this.subCollectionDescription = subCollectionDescription;
        this.registrationDate = registrationDate;
        this.expirationDate = expirationDate;
        this.owner = owner;
        this.securityTag = securityTag;
    }

    @java.lang.SuppressWarnings("all")
    public String getCollectionId() {
        return this.collectionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCollectionIdLabel() {
        return this.collectionIdLabel;
    }

    @java.lang.SuppressWarnings("all")
    public String getCollectionIdAlias() {
        return this.collectionIdAlias;
    }

    @java.lang.SuppressWarnings("all")
    public String getCollectionDescription() {
        return this.collectionDescription;
    }

    @java.lang.SuppressWarnings("all")
    public String getSubCollectionId() {
        return this.subCollectionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getSubCollectionIdLabel() {
        return this.subCollectionIdLabel;
    }

    @java.lang.SuppressWarnings("all")
    public String getSubCollectionIdAlias() {
        return this.subCollectionIdAlias;
    }

    @java.lang.SuppressWarnings("all")
    public String getSubCollectionDescription() {
        return this.subCollectionDescription;
    }

    @java.lang.SuppressWarnings("all")
    public Date getRegistrationDate() {
        return this.registrationDate;
    }

    @java.lang.SuppressWarnings("all")
    public Date getExpirationDate() {
        return this.expirationDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getOwner() {
        return this.owner;
    }

    @java.lang.SuppressWarnings("all")
    public String getSecurityTag() {
        return this.securityTag;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectionId(final String collectionId) {
        this.collectionId = collectionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectionIdLabel(final String collectionIdLabel) {
        this.collectionIdLabel = collectionIdLabel;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectionIdAlias(final String collectionIdAlias) {
        this.collectionIdAlias = collectionIdAlias;
    }

    @java.lang.SuppressWarnings("all")
    public void setCollectionDescription(final String collectionDescription) {
        this.collectionDescription = collectionDescription;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubCollectionId(final String subCollectionId) {
        this.subCollectionId = subCollectionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubCollectionIdLabel(final String subCollectionIdLabel) {
        this.subCollectionIdLabel = subCollectionIdLabel;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubCollectionIdAlias(final String subCollectionIdAlias) {
        this.subCollectionIdAlias = subCollectionIdAlias;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubCollectionDescription(final String subCollectionDescription) {
        this.subCollectionDescription = subCollectionDescription;
    }

    @java.lang.SuppressWarnings("all")
    public void setRegistrationDate(final Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpirationDate(final Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setOwner(final String owner) {
        this.owner = owner;
    }

    @java.lang.SuppressWarnings("all")
    public void setSecurityTag(final String securityTag) {
        this.securityTag = securityTag;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuthorityInformation)) return false;
        final AuthorityInformation other = (AuthorityInformation) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$collectionId = this.getCollectionId();
        final java.lang.Object other$collectionId = other.getCollectionId();
        if (this$collectionId == null ? other$collectionId != null : !this$collectionId.equals(other$collectionId)) return false;
        final java.lang.Object this$collectionIdLabel = this.getCollectionIdLabel();
        final java.lang.Object other$collectionIdLabel = other.getCollectionIdLabel();
        if (this$collectionIdLabel == null ? other$collectionIdLabel != null : !this$collectionIdLabel.equals(other$collectionIdLabel)) return false;
        final java.lang.Object this$collectionIdAlias = this.getCollectionIdAlias();
        final java.lang.Object other$collectionIdAlias = other.getCollectionIdAlias();
        if (this$collectionIdAlias == null ? other$collectionIdAlias != null : !this$collectionIdAlias.equals(other$collectionIdAlias)) return false;
        final java.lang.Object this$collectionDescription = this.getCollectionDescription();
        final java.lang.Object other$collectionDescription = other.getCollectionDescription();
        if (this$collectionDescription == null ? other$collectionDescription != null : !this$collectionDescription.equals(other$collectionDescription)) return false;
        final java.lang.Object this$subCollectionId = this.getSubCollectionId();
        final java.lang.Object other$subCollectionId = other.getSubCollectionId();
        if (this$subCollectionId == null ? other$subCollectionId != null : !this$subCollectionId.equals(other$subCollectionId)) return false;
        final java.lang.Object this$subCollectionIdLabel = this.getSubCollectionIdLabel();
        final java.lang.Object other$subCollectionIdLabel = other.getSubCollectionIdLabel();
        if (this$subCollectionIdLabel == null ? other$subCollectionIdLabel != null : !this$subCollectionIdLabel.equals(other$subCollectionIdLabel)) return false;
        final java.lang.Object this$subCollectionIdAlias = this.getSubCollectionIdAlias();
        final java.lang.Object other$subCollectionIdAlias = other.getSubCollectionIdAlias();
        if (this$subCollectionIdAlias == null ? other$subCollectionIdAlias != null : !this$subCollectionIdAlias.equals(other$subCollectionIdAlias)) return false;
        final java.lang.Object this$subCollectionDescription = this.getSubCollectionDescription();
        final java.lang.Object other$subCollectionDescription = other.getSubCollectionDescription();
        if (this$subCollectionDescription == null ? other$subCollectionDescription != null : !this$subCollectionDescription.equals(other$subCollectionDescription)) return false;
        final java.lang.Object this$registrationDate = this.getRegistrationDate();
        final java.lang.Object other$registrationDate = other.getRegistrationDate();
        if (this$registrationDate == null ? other$registrationDate != null : !this$registrationDate.equals(other$registrationDate)) return false;
        final java.lang.Object this$expirationDate = this.getExpirationDate();
        final java.lang.Object other$expirationDate = other.getExpirationDate();
        if (this$expirationDate == null ? other$expirationDate != null : !this$expirationDate.equals(other$expirationDate)) return false;
        final java.lang.Object this$owner = this.getOwner();
        final java.lang.Object other$owner = other.getOwner();
        if (this$owner == null ? other$owner != null : !this$owner.equals(other$owner)) return false;
        final java.lang.Object this$securityTag = this.getSecurityTag();
        final java.lang.Object other$securityTag = other.getSecurityTag();
        if (this$securityTag == null ? other$securityTag != null : !this$securityTag.equals(other$securityTag)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuthorityInformation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $collectionId = this.getCollectionId();
        result = result * PRIME + ($collectionId == null ? 43 : $collectionId.hashCode());
        final java.lang.Object $collectionIdLabel = this.getCollectionIdLabel();
        result = result * PRIME + ($collectionIdLabel == null ? 43 : $collectionIdLabel.hashCode());
        final java.lang.Object $collectionIdAlias = this.getCollectionIdAlias();
        result = result * PRIME + ($collectionIdAlias == null ? 43 : $collectionIdAlias.hashCode());
        final java.lang.Object $collectionDescription = this.getCollectionDescription();
        result = result * PRIME + ($collectionDescription == null ? 43 : $collectionDescription.hashCode());
        final java.lang.Object $subCollectionId = this.getSubCollectionId();
        result = result * PRIME + ($subCollectionId == null ? 43 : $subCollectionId.hashCode());
        final java.lang.Object $subCollectionIdLabel = this.getSubCollectionIdLabel();
        result = result * PRIME + ($subCollectionIdLabel == null ? 43 : $subCollectionIdLabel.hashCode());
        final java.lang.Object $subCollectionIdAlias = this.getSubCollectionIdAlias();
        result = result * PRIME + ($subCollectionIdAlias == null ? 43 : $subCollectionIdAlias.hashCode());
        final java.lang.Object $subCollectionDescription = this.getSubCollectionDescription();
        result = result * PRIME + ($subCollectionDescription == null ? 43 : $subCollectionDescription.hashCode());
        final java.lang.Object $registrationDate = this.getRegistrationDate();
        result = result * PRIME + ($registrationDate == null ? 43 : $registrationDate.hashCode());
        final java.lang.Object $expirationDate = this.getExpirationDate();
        result = result * PRIME + ($expirationDate == null ? 43 : $expirationDate.hashCode());
        final java.lang.Object $owner = this.getOwner();
        result = result * PRIME + ($owner == null ? 43 : $owner.hashCode());
        final java.lang.Object $securityTag = this.getSecurityTag();
        result = result * PRIME + ($securityTag == null ? 43 : $securityTag.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AuthorityInformation(collectionId=" + this.getCollectionId() + ", collectionIdLabel=" + this.getCollectionIdLabel() + ", collectionIdAlias=" + this.getCollectionIdAlias() + ", collectionDescription=" + this.getCollectionDescription() + ", subCollectionId=" + this.getSubCollectionId() + ", subCollectionIdLabel=" + this.getSubCollectionIdLabel() + ", subCollectionIdAlias=" + this.getSubCollectionIdAlias() + ", subCollectionDescription=" + this.getSubCollectionDescription() + ", registrationDate=" + this.getRegistrationDate() + ", expirationDate=" + this.getExpirationDate() + ", owner=" + this.getOwner() + ", securityTag=" + this.getSecurityTag() + ")";
    }
}
