// Generated by delombok at Tue Apr 30 16:25:30 EDT 2019
/*
 * Copyright 2019 Noblis, Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.noblis.ties.data_binding;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({"groupId", "groupType", "groupDescription", "groupMemberIds", "groupAssertions", "otherInformation"})
public class ObjectGroup {
    @JsonProperty("groupId")
    private String groupId;
    @JsonProperty("groupType")
    private String groupType;
    @JsonProperty("groupDescription")
    private String groupDescription;
    @JsonProperty("groupMemberIds")
    private List<String> groupMemberIds = null;
    @JsonProperty("groupAssertions")
    private Assertions groupAssertions;
    @JsonProperty("otherInformation")
    private List<OtherInformation> otherInformation = null;

    @java.lang.SuppressWarnings("all")
    public ObjectGroup() {
    }

    @java.lang.SuppressWarnings("all")
    public ObjectGroup(final String groupId, final String groupType, final String groupDescription, final List<String> groupMemberIds, final Assertions groupAssertions, final List<OtherInformation> otherInformation) {
        this.groupId = groupId;
        this.groupType = groupType;
        this.groupDescription = groupDescription;
        this.groupMemberIds = groupMemberIds;
        this.groupAssertions = groupAssertions;
        this.otherInformation = otherInformation;
    }

    @java.lang.SuppressWarnings("all")
    public String getGroupId() {
        return this.groupId;
    }

    @java.lang.SuppressWarnings("all")
    public String getGroupType() {
        return this.groupType;
    }

    @java.lang.SuppressWarnings("all")
    public String getGroupDescription() {
        return this.groupDescription;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getGroupMemberIds() {
        return this.groupMemberIds;
    }

    @java.lang.SuppressWarnings("all")
    public Assertions getGroupAssertions() {
        return this.groupAssertions;
    }

    @java.lang.SuppressWarnings("all")
    public List<OtherInformation> getOtherInformation() {
        return this.otherInformation;
    }

    @java.lang.SuppressWarnings("all")
    public void setGroupId(final String groupId) {
        this.groupId = groupId;
    }

    @java.lang.SuppressWarnings("all")
    public void setGroupType(final String groupType) {
        this.groupType = groupType;
    }

    @java.lang.SuppressWarnings("all")
    public void setGroupDescription(final String groupDescription) {
        this.groupDescription = groupDescription;
    }

    @java.lang.SuppressWarnings("all")
    public void setGroupMemberIds(final List<String> groupMemberIds) {
        this.groupMemberIds = groupMemberIds;
    }

    @java.lang.SuppressWarnings("all")
    public void setGroupAssertions(final Assertions groupAssertions) {
        this.groupAssertions = groupAssertions;
    }

    @java.lang.SuppressWarnings("all")
    public void setOtherInformation(final List<OtherInformation> otherInformation) {
        this.otherInformation = otherInformation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ObjectGroup)) return false;
        final ObjectGroup other = (ObjectGroup) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$groupId = this.getGroupId();
        final java.lang.Object other$groupId = other.getGroupId();
        if (this$groupId == null ? other$groupId != null : !this$groupId.equals(other$groupId)) return false;
        final java.lang.Object this$groupType = this.getGroupType();
        final java.lang.Object other$groupType = other.getGroupType();
        if (this$groupType == null ? other$groupType != null : !this$groupType.equals(other$groupType)) return false;
        final java.lang.Object this$groupDescription = this.getGroupDescription();
        final java.lang.Object other$groupDescription = other.getGroupDescription();
        if (this$groupDescription == null ? other$groupDescription != null : !this$groupDescription.equals(other$groupDescription)) return false;
        final java.lang.Object this$groupMemberIds = this.getGroupMemberIds();
        final java.lang.Object other$groupMemberIds = other.getGroupMemberIds();
        if (this$groupMemberIds == null ? other$groupMemberIds != null : !this$groupMemberIds.equals(other$groupMemberIds)) return false;
        final java.lang.Object this$groupAssertions = this.getGroupAssertions();
        final java.lang.Object other$groupAssertions = other.getGroupAssertions();
        if (this$groupAssertions == null ? other$groupAssertions != null : !this$groupAssertions.equals(other$groupAssertions)) return false;
        final java.lang.Object this$otherInformation = this.getOtherInformation();
        final java.lang.Object other$otherInformation = other.getOtherInformation();
        if (this$otherInformation == null ? other$otherInformation != null : !this$otherInformation.equals(other$otherInformation)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ObjectGroup;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $groupId = this.getGroupId();
        result = result * PRIME + ($groupId == null ? 43 : $groupId.hashCode());
        final java.lang.Object $groupType = this.getGroupType();
        result = result * PRIME + ($groupType == null ? 43 : $groupType.hashCode());
        final java.lang.Object $groupDescription = this.getGroupDescription();
        result = result * PRIME + ($groupDescription == null ? 43 : $groupDescription.hashCode());
        final java.lang.Object $groupMemberIds = this.getGroupMemberIds();
        result = result * PRIME + ($groupMemberIds == null ? 43 : $groupMemberIds.hashCode());
        final java.lang.Object $groupAssertions = this.getGroupAssertions();
        result = result * PRIME + ($groupAssertions == null ? 43 : $groupAssertions.hashCode());
        final java.lang.Object $otherInformation = this.getOtherInformation();
        result = result * PRIME + ($otherInformation == null ? 43 : $otherInformation.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ObjectGroup(groupId=" + this.getGroupId() + ", groupType=" + this.getGroupType() + ", groupDescription=" + this.getGroupDescription() + ", groupMemberIds=" + this.getGroupMemberIds() + ", groupAssertions=" + this.getGroupAssertions() + ", otherInformation=" + this.getOtherInformation() + ")";
    }
}
